### ISSUE TITLE
Missing amount validation when voting

### ISSUE THREAD

**Issue by chevdor** [polkassembly/polkassembly#602]
Currently, when voting, the `lock balance` field is empty.

<img width="548" alt="image" src="https://github.com/polkassembly/polkassembly/assets/738724/c1686460-4a91-431f-8dd9-ca561f0ff209">

This is per say not an issue, however there is no validation and users can cast a vote without providing any value.

It may be a stretch to assume that ALL users want to use their full balance when voting by default, but I am confident no user make the effort to vote to end up locking `0`.

A least, some validation should warn the user that they are about to vote with `0` and ask for confirmation that they **really** want to do that. Or better, `empty` should not be considered as a valid value = 0.

Next step would be an option per user setup a pre-filled default lock value as one of the following options:
- percentage of the available balance: 0..100 %
- fixed amount: 0.. N

If the setting is not set, the validation mentioned above could tell the user about this new option an invite them to take advantage of it.

**Comment by gilescope** [comment]
If you knew what the last vote with that account was in terms of voting quantity and conviction you could default to that. That would be cool because the additional lockin of voting this time would only be + x days - if you could calculate that and show that on the UI that would be super cool. Most votes are almost free in terms of additional lock in time if they have voted recently and the UI should hint at that (and also flag if you're increasing the lock duration dramatically from what it currently is).

**Comment by rajdeep7Singh** [comment]
@chevdor @gilescope We are working on this. Should be live soon. Thanks for pointing out
