### ISSUE TITLE
Cannot Reply

### ISSUE THREAD

**Issue by rvalle** [polkassembly/polkassembly#771]
I have posted Polkadot opengov vote 181.

I try to reply to user comments, the UI tells me that my reply was added successfully but never shows up, even after reloading the UI.

 I don't know what is happening but I have two theories:

- There is a bug and replies are not been stored at all.
- There is content moderation in place and the replies need approval.

If we are in the second case, the UI is confusing and I would recommend a modal notification, that requires user to accept, with information about the post being reviewed or something similar.

If you need traces, 5 minutes ago I posted the same/similar replies to Claudio's comment on https://polkadot.polkassembly.io/referenda/181 non of which is being displayed.

**Comment by rvalle** [comment]
ok, I realized that the reason why I could not reply is because the origin of the comment is the discussion and I was trying to reply from the referenda which is also displaying the discussion comments.

I guess this is work in progress as the integration of discussions into referenda is quite recent, or?

**Comment by alphainfinitus** [comment]
Hi @rvalle,

Thank you for taking the time to report this issue.
This has now been fixed with https://github.com/polkassembly/polkassembly/commit/35be5409d5d4ec69c7e97edf7e14d8e4522d65e5

Your feedback is invaluable in helping us improve.

We're now closing this issue, but please don't hesitate to reach out if you encounter any further issues or have additional feedback. The Polkassembly team is here to assist you!

Thanks again,
Mridul

**Comment by rvalle** [comment]
@alphainfinitus no problem. happy to help.
